SSGM_ELVISPRIME_WEB/Controllers/LogisticsInfo/LogisticsInfoController.cs
using SSGM_ELVISPRIME_COMMON.YJIT_Utils;
using SSGM_ELVISPRIME_COMMON.Controllers;
using System;
using System.Web.Mvc;
using SSGM_ELVISPRIME_WEB.Models;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using YJIT.Data;
using Newtonsoft.Json;


namespace SSGM_ELVISPRIME_WEB.Controllers.LogisticsInfo
{
    public class LogisticsInfoController : Controller
    {
        //
        // GET: /Default1/
        public ActionResult Notice()
        {
            return View();
        }
        public ActionResult CBM()
        {
            return View();
        }
        public ActionResult Surcharge()
        {
            return View();
        }
        public ActionResult Incoterms()
        {
            return View();
        }
        public ActionResult PortLocation()
        {
            return View();
        }
        public ActionResult Tariff()
        {
            return View();
        }
        public ActionResult AEOInfo()
        {
            return View();
        }
        public ActionResult Vehicle()
        {
            return View();
        }

        Encryption ec = new Encryption(); //DB_Data - Encryption      
        Con_LogisticsTools CL = new Con_LogisticsTools();
        String strResult = "";
        String strJson = "";

        public class JsonData
        {
            public string vJsonData { get; set; }
        }




        private List<NoticeModel> NoticeList = new List<NoticeModel>();
        public List<DataRow> dtList { get; set; }
        public class pageParam
        {
            public string Option { get; set; }
            public string Type { get; set; }
            public string SearchText { get; set; }
            public int Page { get; set; }
            public string Area { get; set; }
        }
        public string CallAjax(pageParam rtnVal)
        {
            string rtnJson = "";
            try
            {
                if (rtnVal != null)
                {
                    string strOpt = rtnVal.Option;
                    string strType = rtnVal.Type;
                    string strText = rtnVal.SearchText;
                    int pageIndex = rtnVal.Page;

                    ADO_Conn con = new ADO_Conn();
                    DBA dbConn = new DBA(con.ConnectionStr, DbConfiguration.Current.DatabaseType);
                    DataTable dt = dbConn.SqlGet(con.Search_Notice(strOpt, strType, strText, pageIndex));
                    if (dt != null)
                    {
                        if (dt.Rows.Count > 0) rtnJson = JsonConvert.SerializeObject(dt);
                    }

                }
                return rtnJson;
            }
            catch (Exception e) 
            {
                return e.Message;
            }
        }

        public ActionResult notice_view(string id)   //공지사항 상세보기
        {
            if (!string.IsNullOrEmpty(id))
            {
                ADO_Conn con = new ADO_Conn();
                DBA dbConn = new DBA(con.ConnectionStr, DbConfiguration.Current.DatabaseType);
                dbConn.SqlSet(con.Update_ViewCnt(id));
                dbConn.Commit();
                DataTable dt = dbConn.SqlGet(con.Search_NoticeView(id));


                if (dt.Rows.Count > 0)
                {
                    foreach (DataRow dr in dt.Rows)
                    {
                        NoticeList.Add(new NoticeModel
                        {
                            FLAG = dr["FLAG"].ToString(),
                            NOTICE_ID = int.Parse(dr["NOTICE_ID"].ToString()),
                            TITLE = dr["TITLE"].ToString(),
                            CNT = int.Parse(dr["CNT"].ToString()),
                            WRITER = dr["WRITER"].ToString(),
                            USE_YN = dr["USE_YN"].ToString(),
                            NOTICE_YN = dr["NOTICE_YN"].ToString(),
                            REGDT = dr["REGDT"].ToString(),
                            EDITDT = dr["EDITDT"].ToString(),
                            FILE = dr["FILE"].ToString(),
                            FILE_NAME = dr["FILE_NAME"].ToString(),
                            FILE1 = dr["FILE1"].ToString(),
                            FILE_NAME1 = dr["FILE1_NAME"].ToString(),
                            FILE2 = dr["FILE2"].ToString(),
                            FILE_NAME2 = dr["FILE2_NAME"].ToString(),
                            CONTENT = dr["CONTENT"].ToString(),
                            TYPE = dr["TYPE"].ToString()
                        });
                    }
                }
            }
            return View(NoticeList);
        }

        /// <summary>
        /// 분기 / 년 데이터 가져오기
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult fnSetYearQuarter(JsonData value)
        {
            try
            {
                string vJsonData = value.vJsonData.ToString();
                string vEncodeData = "";

                //암호화 걸기
                vEncodeData = ec.encryptAES256(vJsonData);

                strResult = CL.Con_SetYearQuarter(vEncodeData);

                strJson = ec.decryptAES256(strResult);

                return Json(strJson);
            }
            catch (Exception e)
            {
                strJson = e.Message;
                return Json(strJson);
            }
        }

        /// <summary>
        /// 전체(시.도) 데이터 가져오기
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult fnSetAddrState(JsonData value)
        {
            try
            {
                string vJsonData = value.vJsonData.ToString();
                string vEncodeData = "";

                //암호화 걸기
                vEncodeData = ec.encryptAES256(vJsonData);

                strResult = CL.Con_SetAddrState(vEncodeData);

                strJson = ec.decryptAES256(strResult);

                return Json(strJson);
            }
            catch (Exception e)
            {
                strJson = e.Message;
                return Json(strJson);
            }
        }

        /// <summary>
        /// 전체(시.군.구) 데이터 가져오기
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult fnSetAddrCity(JsonData value)
        {
            try
            {
                string vJsonData = value.vJsonData.ToString();
                string vEncodeData = "";

                //암호화 걸기
                vEncodeData = ec.encryptAES256(vJsonData);

                strResult = CL.Con_SetAddrCity(vEncodeData);

                strJson = ec.decryptAES256(strResult);

                return Json(strJson);
            }
            catch (Exception e)
            {
                strJson = e.Message;
                return Json(strJson);
            }
        }

        /// <summary>
        /// 전체(읍,면,동 - 행정동)데이터 가져오기
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult fnSetAddrTownship(JsonData value)
        {
            try
            {
                string vJsonData = value.vJsonData.ToString();
                string vEncodeData = "";

                //암호화 걸기
                vEncodeData = ec.encryptAES256(vJsonData);

                strResult = CL.Con_SetAddrTownship(vEncodeData);

                strJson = ec.decryptAES256(strResult);

                return Json(strJson);
            }
            catch (Exception e)
            {
                strJson = e.Message;
                return Json(strJson);
            }
        }

        /// <summary>
        /// 전체(읍,면,동 - 법정동) 데이터 가져오기
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult fnSetAddrTownship2(JsonData value)
        {
            try
            {
                string vJsonData = value.vJsonData.ToString();
                string vEncodeData = "";

                //암호화 걸기
                vEncodeData = ec.encryptAES256(vJsonData);

                strResult = CL.Con_SetAddrTownship2(vEncodeData);

                strJson = ec.decryptAES256(strResult);

                return Json(strJson);
            }
            catch (Exception e)
            {
                strJson = e.Message;
                return Json(strJson);
            }
        }

        /// <summary>
        /// 항구 기점 데이터 가져오기
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult fnSetSection(JsonData value)
        {
            try
            {
                string vJsonData = value.vJsonData.ToString();
                string vEncodeData = "";

                //암호화 걸기
                vEncodeData = ec.encryptAES256(vJsonData);

                strResult = CL.Con_fnSetSection(vEncodeData);

                strJson = ec.decryptAES256(strResult);

                return Json(strJson);
            }
            catch (Exception e)
            {
                strJson = e.Message;
                return Json(strJson);
            }
        }


        /// <summary>
        /// 할증 데이터 가져오기
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult fnSetPremiumRate(JsonData value)
        {
            try
            {
                string vJsonData = value.vJsonData.ToString();
                string vEncodeData = "";

                //암호화 걸기
                vEncodeData = ec.encryptAES256(vJsonData);

                strResult = CL.Con_SetPremiumRate(vEncodeData);

                strJson = ec.decryptAES256(strResult);

                return Json(strJson);
            }

SSGM_ELVISPRIME_WEB/Views/LogisticsInfo/AEOInfo.cshtml
@{
    ViewBag.Title = "LogisticsTools";
    ViewBag.Sub = "AEOInfo";

    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section Container {

    <script>
        $('.lnb > li:nth-child(1)').addClass('on');
        $('.lnb > li.on .sub_depth li:nth-child(4) a').addClass('on');
    </script>

    <div class="container">
        <div class="sub_visual">
            <div class="inner">
                <h4 class="subtitle">법령정보</h4>
            </div>
        </div>
        <div class="fixed_in type2 logistics">
            <div class="aeo_info">
                <table class="list_type1 tools">
                    <colgroup>
                        <col class="w4" />
                        <col class="w10" />
                        <col class="w11" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th>번호</th>
                            <th>법규명</th>
                            <th>비고</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=165305#0000" target="_blank">관세법</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=168362#0000" target="_blank">관세법 시행령</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=169106#0000" target="_blank">관세법 시행규칙</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=150397#0000" target="_blank">대외무역법</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=164827#0000" target="_blank">대외무역법 시행령</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000019345" target="_blank">대외무역관리규정</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>7</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=132469#0000" target="_blank">외국환거래법</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>8</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=164724#0000" target="_blank">외국환거래법 시행령</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>9</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/admRulInfoP.do?admRulSeq=2100000016827" target="_blank">외국환거래규정</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>10</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=162513#0000" target="_blank">물류정책기본법</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>11</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=150910#0000" target="_blank">물류정책기본법 시행령</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>12</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=158590#0000" target="_blank">물류정책기본법 시행규칙</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>13</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000004984" target="_blank">보세운송에 관한 고시</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>14</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000007808" target="_blank">보세화물관리에 관한 고시</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>15</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000004982" target="_blank">보세화물 입출항 하선 하기 및 적재에 관한 고시</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>16</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000015609" target="_blank">수입통관 사무처리에 관한 고시</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>17</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000012515" target="_blank">원산지제도 운영에 관한 고시</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>18</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000008341" target="_blank">전략물자 수출입 통관에 관한 고시</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>19</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000019567" target="_blank">종합인증 우수업체공인 및 관리업무에 관한 고시</a></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>20</td>
                            <td class="left"><a href="https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000008338" target="_blank">화물운송주선업자의 등록 및 관리에 관한 고시</a></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

SSGM_ELVISPRIME_WEB/Views/LogisticsInfo/notice_view.cshtml
@{
    ViewBag.Title = "Company";
    ViewBag.Sub = "notice_view";

    Layout = "~/Views/Shared/_SubLayout.cshtml";

    string setLang = "";
    if (HttpContext.Current.Session["Language"] == null)
    {
        if (Request.Params["Language"] == null)
        {
            setLang = "KO";
            HttpContext.Current.Session["Language"] = "KO";
        }
    }
    else
    {
        if (Request.Params["Language"] == null)
        {
            setLang = HttpContext.Current.Session["Language"].ToString();
        }
        else
        {
            setLang = "EN";
        }
    }

    if (string.IsNullOrEmpty(setLang))
    {
        setLang = "KO";
    }
}

@section Container {
    <script>
            $('.lnb > li:nth-child(4)').addClass('on');
            $('.lnb > li.on .sub_depth li:nth-child(1) a').addClass('on');
    </script>
    <!-- E : sub-nav : dropdown -->
    <!-- S : Main -->
    <main class="main sub-main" id="contents">
        <section class="section">
            <div class="container" style="padding-top:30px;">
                <div class="sub_visual" id="Schedule">
                    <div class="inner">
                        <h4 class="subtitle">
                            <span>
                                Start Your Business<br />
                                with <strong>FairConline</strong>
                            </span>
                        </h4>
                    </div>
                </div>
                @*@{
            foreach (var rowItem in Model)
            {
                if (@rowItem.FLAG == "VIEW")
                {
                    <div class="board_view">
                        <div class="title_row">
                            <div class="col">
                                <h4 class="title">@Html.Raw(@rowItem.TITLE)</h4>
                            </div>
                            <div class="col etc">
                                <span>@Html.Raw(@rowItem.WRITER)</span>
                                <span>@Html.Raw(@rowItem.REGDT.Substring(0, 10))</span>
                                <span>조회수 : @Html.Raw(@rowItem.CNT)</span>
                            </div>
                        </div>
                        <div class="cont_row">
                            @Html.Raw(@rowItem.CONTENT)
                        </div>
                        @{
                            if (!string.IsNullOrEmpty(@rowItem.FILE) || !string.IsNullOrEmpty(@rowItem.FILE1) || !string.IsNullOrEmpty(@rowItem.FILE2))
                            {
                                <div class="cont_row">
                                    첨부파일 :
                                    <a href="@Url.Action("Download", "File", new { filename = @rowItem.FILE_NAME, rFilename = @rowItem.FILE })">@rowItem.FILE_NAME</a> &nbsp;&nbsp;
                                    <a href="@Url.Action("Download", "File", new { filename = @rowItem.FILE_NAME1, rFilename = @rowItem.FILE1 })">@rowItem.FILE_NAME1</a> &nbsp;&nbsp;
                                    <a href="@Url.Action("Download", "File", new { filename = @rowItem.FILE_NAME2, rFilename = @rowItem.FILE2 })">@rowItem.FILE_NAME2</a> &nbsp;&nbsp;
                                </div>
                            }
                        }
                    </div>
                }
            }
        }*@
            <div class="sub_cover">
                <div class="fixed_in type2">
                    <table class="table-view-01 txt-mt">
                        <caption>
                            <span class="hidden">상세 입니다.</span>
                        </caption>
                        <colgroup>
                            <col width="90px" />
                            <col width="*" />
                        </colgroup>
                        <tbody>
                            @{
                                foreach (var rowItem in Model)
                                {
                                    if (@rowItem.FLAG == "VIEW")
                                    {
                                        <tr>
                                            <td colspan="2" class="clear-fix tit_box">
                                                @{
                                                    if (rowItem.TYPE == "0")
                                                    {
                                                        <p class="tit"><span class="type_t">공지사항</span>@Html.Raw(@rowItem.TITLE)</p>
                                                    }
                                                    else
                                                    {
                                                        <p class="tit"><span class="type_t">스케줄</span>@Html.Raw(@rowItem.TITLE)</p>
                                                    }
                                                }

                                                <p class="tbl_detail_span mt_05">
                                                    <span class="name">@Html.Raw(@rowItem.WRITER)</span>
                                                    @{
                                                        if (Html.Raw(@rowItem.EDITDT) != null)
                                                        {
                                                            <span class="date">@Html.Raw(@rowItem.REGDT.Split(' ')[0])</span>
                                                        }
                                                        else
                                                        {
                                                            <span class="date">@Html.Raw(@rowItem.EDITDT.Split(' ')[0])</span>
                                                        }


                                                    }
                                                </p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>첨부파일</td>
                                            <td>
                                                @{
                                                    if (!string.IsNullOrEmpty(@rowItem.FILE))
                                                    {
                                                        <p class="addfile_txt"><a href="@Url.Action("Download", "File", new { filename = @rowItem.FILE_NAME, rFilename = @rowItem.FILE })">@rowItem.FILE_NAME</a> </p>
                                                    }
                                                    if (!string.IsNullOrEmpty(@rowItem.FILE1))
                                                    {
                                                        <p class="addfile_txt"><a href="@Url.Action("Download", "File", new { filename = @rowItem.FILE_NAME1, rFilename = @rowItem.FILE1 })">@rowItem.FILE_NAME1</a> </p>
                                                    }
                                                    if (!string.IsNullOrEmpty(@rowItem.FILE2))
                                                    {
                                                        <p class="addfile_txt"><a href="@Url.Action("Download", "File", new { filename = @rowItem.FILE_NAME2, rFilename = @rowItem.FILE2 })">@rowItem.FILE_NAME2</a> </p>
                                                    }
                                                }
                                            </td>
                                        </tr>


                                        <tr>
                                            <td colspan="2">
                                                <div class="board-box">@Html.Raw(rowItem.CONTENT)</div>
                                            </td>
                                        </tr>
                                    }
                                }
                            }
                            <!--<tr>
                <td colspan="2" class="clearfix tit_box">
                    <p class="tit"><span class="type_t">뷴류노출</span>제목 노출</p>
                    <p class="tbl_detail_span mt_05">
                        <span class="name">관리자</span>
                        <span class="date">2022.01.01</span>-->
                            <!-- <span class="check_01">조회:51</span> -->
                            <!--</p>
                    </td>
                </tr>-->
                            @*<tr>
                        <td colspan="2">
                            <div class="board-box">@Html.Raw()</div>
                        </td>
                    </tr>*@
                        </tbody>
                    </table>
                    <div class="mt_40 text_right board_view_btn_box">
                        <a href="@Url.Action("notice","LogisticsInfo")" class="btn-type-02 px-6 py-2">목록</a>
                    </div>

                    <div class="border-list-type mt_30">
                        <ul>
                            @{
                                string strPrev = "";
                                string idPrev = "javascript:void(0)";
                                string strNext = "";
                                string idNext = "javascript:void(0)";

                                foreach (var rowItem in Model)
                                {
                                    if (@rowItem.FLAG == "PREV")
                                    {
                                        strPrev = @rowItem.TITLE;
                                        if (!string.IsNullOrEmpty(strPrev)) idPrev = "/LogisticsInfo/notice_view?id=" + @rowItem.NOTICE_ID;
                                    }
                                    else if (@rowItem.FLAG == "NEXT")
                                    {
                                        strNext = @rowItem.TITLE;
                                        if (!string.IsNullOrEmpty(strNext)) idNext = "/LogisticsInfo/notice_view?id=" + @rowItem.NOTICE_ID;
                                    }
                                }

                                if (string.IsNullOrEmpty(strPrev)) { strPrev = "이전글이 없습니다."; }
                                if (string.IsNullOrEmpty(strNext)) { strNext = "다음글이 없습니다."; }

                                <li>
                                    <a href="@Html.Raw(idPrev)" title="이전">
                                        <div class="clearfix">
                                            <div class="left list-up-bg list-title">이전</div>
                                            <div class="left w-con">@Html.Raw(strPrev)</div>
                                        </div>
                                    </a>
                                </li>
                                <li class="border-none">
                                    <a href="@Html.Raw(idNext)" title="다음">
                                        <div class="clearfix">
                                            <div class="left list-down-bg list-title">다음</div>
                                            <div class="left w-con">@Html.Raw(strNext)</div>
                                        </div>
                                    </a>
                                </li>
                            }
                            @*<li>
                        <a href="/Company/notice_view?id=5" title="이전">
                            <div class="clearfix">
                                <div class="left list-up-bg list-title">이전</div>
                                <div class="left w-con">이전글</div>
                            </div>
                        </a>
                    </li>
                    <li class="border-none">
                        <a href="#" title="다음">
                            <div class="clearfix">
                                <div class="left list-down-bg list-title">다음</div>
                                <div class="left w-con">다음 글이 없습니다.</div>
                            </div>
                        </a>
                    </li>*@
                        </ul>
                    </div>
                </div>
            </div>
            </div>
        </section>
    </main>
    <!-- E : Main -->
}

}